

#Lib_src		=	Exception.cpp	Exception.h	_Exception.h
test_src	=	test.cpp

exception_test	:	$(test_src)	
	c++ -Wall test.cpp -o exception_test;	

run		:	exception_test
	./exception_test;

clean	:
	rm	exception_test;


