#*
#* File		:Makefile of cstd_file
#* Author	:tangyu
#* Date		:2011-12-05 00:00:00
#* LastMod	:2011-12-06 00:00:00
#*

c = gcc -std=c99
c++ = g++
C_Flag = -Wall -c
C++_Flag = -Wall -c

First_glance	:	cstd_file.c
	$(c) -o cstd_file cstd_file.c

