#*
#* File		:Makefile of Linux_program
#* Author	:tangyu
#* Date		:2011-12-05 00:00:00
#* LastMod	:2011-12-05 00:00:00
#*


c = gcc -std=c99
cpp = g++

c_Flag = -Wall
cpp_Flag = -Wall

First_glance	:	First_glance.c
	$(c) $(c_Flag) -o First_glance First_glance.c
